services:
  frontend:
    build: mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern

  backend:
    build: mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo_data:
    driver: local
